# Run cargo tests in a Solaris VM.
#
# A normal rustup install fails on Solaris 11.4 as of 2023-08, as does an attempt to install via the
# pkg tool, so this is currently disabled.
#
# See https://github.com/vmactions/solaris-vm

on: workflow_dispatch

name: solaris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run tests in Solaris VM
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        prepare: |
          pkg change-facet facet.devel=true
          pkgutil -y -i curl
          pkg install developer/rust/rustc developer/rust/cargo
          echo "~~~~ rustc --version ~~~~"
          rustc --version

        run: |
          export PATH="${HOME}/.cargo/bin:$PATH"
          ls -la
          cargo build --jobs 1 --no-default-features --verbose
          cargo test --jobs 1 --no-default-features --verbose
